### ISSUE TITLE
Request access to the Jupyter notebook with GPU.

### ISSUE THREAD

**Issue by engkufizz** [malaysia-ai/Jupyterhub#11]
**What is your name?**
Tengku

**What is your title? no need to mention company.**
Network engineer

**What can you help?**
Build some useful models for public

**Additional context about yourself (please brag)**
I have tried to build a model https://github.com/engkufizz/LLaMA-2-Datacom

**Comment by huseinzol05** [comment]
cuba try, https://jupyter.us.mesolitica.com/vscode/?folder=/home/ubuntu

<img width="1449" alt="Screenshot 2023-10-26 at 3 20 28 PM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/15d0a1d6-e4db-4e97-a7e6-eb12e2915e63">

**Comment by huseinzol05** [comment]
close the issue kalau boleh access, make sure read about this https://github.com/malaysia-ai/jupyter-gpu#auto-restart-script

**Comment by engkufizz** [comment]
Nanti saya apply semula lah, tengah x free lagi 🙇🏻‍♂️ sorry2 for the inconvenience
