### ISSUE TITLE
Humble Intro

### ISSUE THREAD

**Issue by Ezaryf** [malaysia-ai/Jupyterhub#14]
I'm Ezaryf bin Hamdan and im 21 years old. I'll turn 22 on the 1st of January

I am a CS final-year student who invests half of my daily life in learning AI

I am still in the venture of gaining knowledge as much as I can while studying. Could provide ideas that couldn't be developed due to the time constraint as well as potato gear.

I'm a degree student who previously worked at two development companies that sharpened my knowledge. I started to learn AI during the first day of my diploma (developing object detection using TensorFlow). Among the students, I've become the one to be sought out if major issues occur and to ask for any advice, particularly during this FYP season. Despite being younger than everyone in my batch, I always had a huge impact on the development of any project for my study, from developing a website to processing an image.

Check me out on my professional profile: https://www.linkedin.com/in/ezaryf/

**Comment by huseinzol05** [comment]
noted. will give access after i wake up tomorrow

**Comment by Ezaryf** [comment]
thank you for the response, sir
