### ISSUE TITLE
Mohon access. Nak contribute semampu yang boleh. 

### ISSUE THREAD

**Issue by Moiralah** [malaysia-ai/Jupyterhub#15]
**What is your name?**
Humaira Binti Idris
**What is your title? no need to mention company.**
Intern Data Analytic + freelance
**What can you help?**
Web scraping dan lain-lain.
**Additional context about yourself (please brag)**
I am a fast learner. I hope I can contribute more as I learn more for this cause. Hidup Malaysia AI. 
Saya ada inform Aisyah untuk contribute. Hari Sabtu malam Ahad nanti ada discussion dgn Aisyah and other girls untuk Malaysia AI, nanti nak minta tunjuk ajar Aisyah utk setup semua. Jadi saya harap En dapat luluskan permohonan access saya. 

Disini saya ingin mengucapakan jutaan terima kasih yang tidak terhingga kerana memulakan inisiatif ini. Besar jasa En. pada Malaysia terutama bahasa melayu.

**Comment by huseinzol05** [comment]
Hi, nanti bila aisyah free, kita adakan sesi server access ye.
