### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by arifikmal** [malaysia-ai/Jupyterhub#19]
**What is your name?**
Hi my name is Arif
**What is your title? no need to mention company.**
Junior Programmer
**What can you help?**
I will look at what I can help
**Additional context about yourself (please brag)**
I have been working less than 1year as Junior Programmer. My work primarily revolves around utilizing OpenCV, YOLO for object detection, OCR, and handwriting recognition. Additionally, I've been involved in building end-to-end MLOps. While I may not have extensive experience, I'm here to both learn and contribute to the open-source community. Currently exploring NLP and I think this is the right place to learn.

**Comment by huseinzol05** [comment]
Join some discussion in the discord

**Comment by arifikmal** [comment]
okay noted
