### ISSUE TITLE
Request Access to GPU server

### ISSUE THREAD

**Issue by HazmanNaim** [malaysia-ai/Jupyterhub#21]
**What is your name?**
Hazman Naim Bin Ahsan

**What is your title? no need to mention company.**
AI Developer (on-job-training) + Aspiring AI Scientist

**What can you help?**
Data scraping, and anything that I can contribute for LLM project. I am open to anything/collaboration.

**Additional context about yourself (please brag)**
Right now, I am doing my on-job-training as an AI developer, collaborating with the backend team to create applications using AI. Outside of work, I enjoy exploring machine learning and AI as a hobby. I have connected with fellow AI practitioners on Kaggle, and together, we have formed a team to participate in a research project competition focused on medical image segmentation. Having access to advanced hardware is really beneficial for our project.

**Comment by huseinzol05** [comment]
we are looking into multimodal, maybe can help us.

**Comment by HazmanNaim** [comment]
> we are looking into multimodal, maybe can help us.

Sounds interesting! I'm open to learning and exploring into multimodal stuff, but I'm a total new to LLM. Any resources you recommend for me to start learning? Maybe we can have a discussion later to chat about it 😄?

**Comment by huseinzol05** [comment]
join je discuss dalam discord

**Comment by HazmanNaim** [comment]
> join je discuss dalam discord

Okay boleh, nanti saya join
