### ISSUE TITLE
Salam, saya newbie

### ISSUE THREAD

**Issue by mindscapexyz** [malaysia-ai/Jupyterhub#23]
**What is your name?**
Halim shukor

**What is your title? no need to mention company.**
Ml engineer

**What can you help?**
Saya boleh code python aws, ada knowledge and experience aws cloud, tapi tak mahir llm

**Additional context about yourself (please brag)**
Ada pengalaman buat ml ops utk CV

**Comment by huseinzol05** [comment]
please chat with us first in discord, last time we had a person mining gpu
