### ISSUE TITLE
Request Access

### ISSUE THREAD

**Issue by Englios** [malaysia-ai/Jupyterhub#24]
**What is your name?**
Muhammad Alif Aiman

**What is your title? no need to mention company.**
I am currently a student, that will graduate within next month

**What can you help?**
Currently for my skillset,I think I can scrape websites to get data for the team.I do have a prospect on doing more such as training and engineering more complex models. All in all I'm joining because i want to learn more and help your endeavours

**Additional context about yourself (please brag)**
I actually a physics student who really is passionate about learning new things,Id say that I am a very quick learner and can digest complex concepts fast.Currently on my own,I am learning more about Reinforcement Learning and dipping my toes in NLP.I have a prospect of learning more about AI on my own first ,before going for postgraduate programs in 2 years time, in other words I'd like to get my hands dirty first.

Some experience of mine within this field,would be my internship,in which i emplyed Adversarial Attacks to improve on CV model robustness.

**Comment by huseinzol05** [comment]
please chat with us first in discord, last time we had a person mining gpu
