### ISSUE TITLE
Request Access to Contribute to Training (?)

### ISSUE THREAD

**Issue by nudin10** [malaysia-ai/Jupyterhub#25]
**What is your name?**
Nudin
**What is your title? no need to mention company.**
Software Engineer (BackEnd)
**What can you help?**
Train model. I am also fairly familiar with AWS as part of my job (havent deployed anything yet tho). Want to learn by joining this.
**Additional context about yourself (please brag)**
I have experience with test automation (end to end (Playwright) , API (Postman, Newman) , performance (k6, docker, influxdb). I created my own cli program to prepare test data because I am too lazy to do repetitive things. It is still being used by the QA team today. I am also self learned (I didnt take IT/CS/SWE). I currently use Golang as a backend engineer but I am familiar with Python and JavaScript also. I am beginer-ish with machine-learning, took an elective during degree, taking masters now (mainly for credentials). I find myself lazing around so I need to get involved in something that can force me to not be lazy. Thanks.

**Comment by huseinzol05** [comment]
nice, please have a conversation first at discord, pm me at husein.zolkepli discord

**Comment by nudin10** [comment]
Thanks. I'll drop by once my schedule is a bit clearer. Currently a bit occupied 😥 . Also saya melayu ahaha cakap ganu pun boleh.

**Comment by Eldo420** [comment]
Untuk meminta akses bagi menyumbang kepada latihan projek `malaysia-ai / jupyter-gpu` di GitHub, anda perlu mengikuti beberapa langkah. Berikut adalah panduan langkah demi langkah dalam Bahasa Malaysia:

1. **Buat Akaun GitHub:**
   - Jika anda belum mempunyai akaun GitHub, pergi ke laman [GitHub](https://github.com/) dan daftar akaun baru.

2. **Log Masuk ke Akaun GitHub:**
   - Masukkan nama pengguna dan kata laluan anda untuk log masuk ke akaun GitHub anda.

3. **Cari Repositori `malaysia-ai / jupyter-gpu`:**
   - Anda boleh mencari repositori ini dengan menaip `malaysia-ai / jupyter-gpu` di bar carian GitHub.

4. **Pergi ke Repositori:**
   - Klik pada pautan repositori `malaysia-ai / jupyter-gpu` untuk pergi ke halaman utama repositori tersebut.

5. **Fork Repositori:**
   - Klik pada butang "Fork" di sudut kanan atas untuk membuat salinan repositori ke akaun GitHub anda sendiri.

6. **Clone Repositori Forked ke Komputer Anda:**
   - Buka terminal atau command prompt di komputer anda dan taip arahan berikut:
     ```sh
     git clone https://github.com/USERNAME/jupyter-gpu.git
     ```
     Gantikan `USERNAME` dengan nama pengguna GitHub anda.

7. **Buat Cawangan Baru:**
   - Masuk ke direktori repositori:
     ```sh
     cd jupyter-gpu
     ```
   - Buat cawangan baru untuk membuat perubahan:
     ```sh
     git checkout -b nama-cawangan-anda
     ```
     Gantikan `nama-cawangan-anda` dengan nama yang sesuai untuk cawangan baru anda.

8. **Buat Perubahan dan Komit:**
   - Lakukan perubahan yang diperlukan dalam repositori.
   - Setelah membuat perubahan, tambahkan dan komit perubahan:
     ```sh
     git add .
     git commit -m "Keterangan perubahan anda"
     ```

9. **Push Cawangan ke Repositori Forked Anda:**
   - Push cawangan baru ke repositori forked anda di GitHub:
     ```sh
     git push origin nama-cawangan-anda
     ```

10. **Buat Pull Request:**
    - Pergi ke halaman repositori forked anda di GitHub.
    - Anda akan melihat satu mesej yang bertanya jika anda ingin membuat "Pull Request". Klik pada butang "Compare & Pull Request".
    - Isikan keterangan mengenai perubahan yang telah anda buat dan klik pada butang "Create Pull Request".

11. **Tunggu Ulasan:**
    - Pemilik atau penyelenggara repositori `malaysia-ai / jupyter-gpu` akan menyemak pull request anda. Mereka mungkin memberi komen atau meminta perubahan tambahan sebelum menerima pull request anda.

12. **Dapatkan Akses:**
    - Setelah pull request anda diterima, anda mungkin akan diminta untuk menyumbang lebih lanjut atau diberi akses tambahan bergantung kepada keperluan projek.

Dengan mengikuti langkah-langkah ini, anda boleh meminta akses dan menyumbang kepada latihan atau pembangunan projek `malaysia-ai / jupyter-gpu`. Selamat mencuba!
