### ISSUE TITLE
Mr. 

### ISSUE THREAD

**Issue by renaissance2005** [malaysia-ai/Jupyterhub#26]
My name is David Lau Keat Jin.

I am a researcher in UTM sponsored by the Government of Malaysia.  

I have attended an online discussion with Mesolitica on 18 Jan 2024 and introduced myself in the forum. 

What Mesolitica has done so far with locally-bred language models is impressive and I wish to contribute by producing research paper and testing/improving the developed models. I have used other models for RAG before this.

**Comment by huseinzol05** [comment]
<img width="638" alt="Screenshot 2024-01-18 at 1 18 32 PM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/b7def0ee-c62e-4a4b-9e03-58dd752b7ee5">

invited, after that, try to access https://jupyter.us.mesolitica.com/
