### ISSUE TITLE
Add support for Mixtra

### ISSUE THREAD

**Issue by RohitRathore1** [malaysia-ai/Jupyterhub#27]
**What is your name?**
Rohit Singh Rathaur

**What is your title? no need to mention company.**
Independent Researcher

**What can you help?**

**Additional context about yourself (please brag)**

**Comment by RohitRathore1** [comment]
Hi @huseinzol05, does it mean I have got the access? If yes, then how can I proceed further?

**Comment by huseinzol05** [comment]
no u do not, Malaysia-AI only available for Malaysian and we focused on Malaysian context development.
