### ISSUE TITLE
Request GPU

### ISSUE THREAD

**Issue by radenmuaz** [malaysia-ai/Jupyterhub#28]
**What is your name?**
Raden Muhammad Mu'az
**What is your title? no need to mention company.**
Senior ML Engineer
**What can you help?**
I can do model compression works (distillation, pruning, quantization)
and efficient on-device inference code (kv-cache, async inference)
**Additional context about yourself (please brag)**

**Comment by huseinzol05** [comment]
lah awat tak habaq hg dah request

**Comment by huseinzol05** [comment]
<img width="636" alt="Screenshot 2024-01-27 at 7 11 51 PM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/cec675ba-1187-43b1-9f9c-fefd61d39554">

pastu try masuk https://jupyter.us.mesolitica.com/
