### ISSUE TITLE
Request Access Server

### ISSUE THREAD

**Issue by FarisIrfxn** [malaysia-ai/Jupyterhub#29]
**What is your name?**
-Faris Irfan

**What is your title? no need to mention company.**
- AI Research & Development

**What can you help?**
- Quantize LLM to GGUF

**Additional context about yourself (please brag)**
Fun fact, I have always enjoyed exploring computer-related matters since I was young. So, during my SPM I chose computer science. However, due to certain reasons, I accidentally ended up pursuing Animation in my diploma. Eventually, I completed an internship at a company where I successfully demonstrated the use of AI available on the internet. As a result, they offered me a job in the field of AI, even though my knowledge in IT is limited and still relies heavily on YouTube LOL.

**Comment by huseinzol05** [comment]
<img width="633" alt="Screenshot 2024-01-31 at 11 34 22 PM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/2b588335-d351-4f9e-a7e9-bd09d9d3cb4b">

after that access https://jupyter.us.mesolitica.com/
