### ISSUE TITLE
Newbie request to join Mesolitica server

### ISSUE THREAD

**Issue by webdevsha** [malaysia-ai/Jupyterhub#30]
**What is your name?**
Shafira Noh (https://shafiranoh.com)

**What is your title? no need to mention company.**
AI Safety researcher

**What can you help?**
1. For the starter now, I am exploring first what have been done.
2. One of my interest that interesect with MaLLam so far is in indigenous knowledge exploration: that could be either in expanding the data, training the data, ... but beyond this, I wanna get to know the community first, see how best I can contribute: let me know! 

**Additional context about yourself (please brag)**
Thank you to brother Husein and Aishah Razak for the very warm convo on LinkedIn. Hope to learn more from you guys. 

I am working on my own community web hub in Sijangkang where I aim to casualize more digital stuffs to folks in my kampung, extension of my 2021's Malaysian Parliamentary Fellowship on digitalization. I finished my AI Safety Camp last year, focusing on how Islamic economics could aid in building safer/ fairer AI labour supply chain. I am applying MA in UiTM in AI, as I wanna lead more local community on the ground. Hope to write more this year more properly too.

**Comment by huseinzol05** [comment]
manteeeep

**Comment by huseinzol05** [comment]
lawanya website puan

**Comment by huseinzol05** [comment]
<img width="613" alt="Screenshot 2024-02-01 at 12 37 21 PM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/a040ec2b-fbf0-40de-b31b-a4154447075d">

after that access https://jupyter.us.mesolitica.com/

**Comment by webdevsha** [comment]
> manteeeep

Tuan-puan sekalian kat sini lagi manteppppp; terima kasih sudi tambah masuk! Masih mencacau lagi nak faham how it works niii

**Comment by webdevsha** [comment]
> <img alt="Screenshot 2024-02-01 at 12 37 21 PM" width="613" src="https://private-user-images.githubusercontent.com/19810909/301386589-a040ec2b-fbf0-40de-b31b-a4154447075d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjM5MDQsIm5iZiI6MTcwNjc2MzYwNCwicGF0aCI6Ii8xOTgxMDkwOS8zMDEzODY1ODktYTA0MGVjMmItZmJmMC00MGRlLWIzMWItYTQxNTQ0NDcwNzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1MDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZWI1NDQ5MmY5OGRkNTFhMDI5YjEzNTMyNjliZDZhMWIxNzcxMWU3NzNjYTJiOTk0NzQ4ODJlMTU0MTYxMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYDEZq54vZEw9A3nZkC7FV5iW-y4AktIvKSm7O55c9E">
> after that access https://jupyter.us.mesolitica.com/

Kalau dapat 403 Forbidden kena cuba apa ya? 
![Uploading Screenshot 2024-02-01 at 1.00.00 PM.png…]()
