### ISSUE TITLE
Jupyter-gpu access for data scraping/crawling

### ISSUE THREAD

**Issue by fattahharith** [malaysia-ai/Jupyterhub#31]
**What is your name?**

Fattah Harith (Fattah for short)

**What is your title? no need to mention company.**

software engineer

**What can you help?**

data scraping/crawling in general but potentially other stuffs too like data cleaning, preparing llm training scripts, etc. (anything really, depending on usecase)

**Additional context about yourself (please brag)**

Used to be a full-stack engineer/architect under Network Intelligence & Analytics team in a GLC company for ~3 years before current role. 

I share high-quality tech memes and a music enthusiast, we could talk a lot about that too!

**Comment by KamarulAdha** [comment]
Welcome to our club.

Please access the server via the link I sent on Discord.

**Comment by fattahharith** [comment]
which link?

**Comment by KamarulAdha** [comment]
Resent.
![image](https://github.com/malaysia-ai/jupyter-gpu/assets/52944294/9d101d29-714a-47f8-a94e-df85ebbb42f9)

**Comment by fattahharith** [comment]
invitation accepted & access to server has been verified, thanks for the help!
