### ISSUE TITLE
Access Request for Jupter Notebook with GPU

### ISSUE THREAD

**Issue by zhulinchng** [malaysia-ai/Jupyterhub#33]
**What is your name?**
Zhu Lin
**What is your title? no need to mention company.**
Senior Intelligent Automation Engineer
**What can you help?**
I can help with  improving existing open source AI models to make it more accessible, and provide technical support from time to time.
**Additional context about yourself (please brag)**
I am eager to collaborate with other experts in the field to develop and improve AI models and projects that can benefit society as a whole. My experience in developing and implementing integrated machine learning automation solutions, as well as my proficiency in programming languages and frameworks, makes me a valuable asset to the project.

**Comment by Eldo420** [comment]
Untuk memberikan akses kepada pengguna untuk Jupyter Notebook dengan GPU di repositori `malaysia-ai / jupyter-gpu`, anda boleh mengikuti langkah-langkah berikut. Panduan ini merangkumi cara memberikan akses dan menyediakan persekitaran yang diperlukan untuk notebook Jupyter dengan GPU. Panduan ini dalam Bahasa Malaysia.

### Langkah 1: Memberikan Akses melalui GitHub
1. **Log Masuk ke Akaun GitHub Anda:**
   - Masukkan nama pengguna dan kata laluan anda untuk log masuk.

2. **Pergi ke Repositori `malaysia-ai / jupyter-gpu`:**
   - Cari repositori `malaysia-ai / jupyter-gpu` dan klik padanya untuk pergi ke halaman repositori tersebut.

3. **Pergi ke `Settings`:**
   - Pada halaman repositori, cari tab `Settings` yang biasanya berada di sebelah kanan tab `Insights`.

4. **Pergi ke `Manage Access`:**
   - Klik pada `Manage Access` di dalam menu sebelah kiri.

5. **Invite Collaborator:**
   - Klik pada butang `Invite a collaborator`.
   - Masukkan nama pengguna GitHub orang yang anda ingin berikan akses (dalam kes ini, individu dengan permintaan akses #33).
   - Klik pada butang `Add <username>` untuk menghantar jemputan.

### Langkah 2: Menyediakan Persekitaran Jupyter Notebook dengan GPU
Untuk memberikan pengguna akses kepada Jupyter Notebook dengan sokongan GPU, berikut adalah panduan langkah demi langkah untuk menyediakan persekitaran:

1. **Pasang Anaconda:**
   - Anaconda adalah pengurus persekitaran popular untuk Python. Muat turun dan pasang dari [sini](https://www.anaconda.com/products/distribution).

2. **Pasang CUDA dan cuDNN (untuk pengguna NVIDIA GPU)**
   - Ikuti panduan rasmi dari NVIDIA untuk memasang [CUDA](https://developer.nvidia.com/cuda-downloads) dan [cuDNN](https://developer.nvidia.com/cudnn).

3. **Buat Persekitaran Anaconda:**
   - Buka terminal atau Anaconda Prompt dan taip:
     ```sh
     conda create -n jupyter-gpu python=3.8
     conda activate jupyter-gpu
     ```

4. **Pasang Jupyter Notebook:**
   - Dalam Anaconda Prompt, pasang Jupyter Notebook:
     ```sh
     conda install jupyter
     ```

5. **Pasang Pustaka Tambahan (TensorFlow/PyTorch/Keras dengan GPU):**
   - Pilih pustaka yang ingin digunakan. Contohnya, untuk TensorFlow GPU:
     ```sh
     pip install tensorflow-gpu
     ```
   - Untuk PyTorch dengan sokongan GPU:
     ```sh
     conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
     ```

6. **Mulakan Jupyter Notebook:**
   - Untuk memulakan Jupyter Notebook, taip:
     ```sh
     jupyter notebook
     ```
   - Ini akan membuka Jupyter Notebook di pelayar web anda.

7. **Uji Penggunaan GPU:**
   - Buat notebook baru dan cuba uji sama ada GPU tersedia. Contoh kod untuk TensorFlow:
     ```python
     import tensorflow as tf
     print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
     ```

### Langkah 3: Dokumentasi dan Bantuan
1. **Sediakan Dokumentasi:**
   - Buat dokumen README yang jelas tentang cara untuk menyediakan dan menggunakan Jupyter Notebook dengan GPU dalam projek `malaysia-ai / jupyter-gpu`.

2. **Bantuan Teknikal:**
   - Sediakan panduan atau saluran bantuan di mana pengguna boleh menghubungi pasukan sokongan teknikal jika mereka mengalami masalah semasa menggunakan persekitaran ini.

Dengan mengikuti langkah-langkah di atas, anda boleh memberikan akses dan menyediakan persekitaran yang betul bagi pengguna yang ingin menggunakan Jupyter Notebook dengan GPU di projek `malaysia-ai / jupyter-gpu`.
