### ISSUE TITLE
Request server access

### ISSUE THREAD

**Issue by Elissa-Irhamy** [malaysia-ai/Jupyterhub#35]
**What is your name?** 
Elissa Irhamy

**What is your title? no need to mention company.** 
Data Science Specialist

**What can you help?** 
Adding publicly available non commercial IMDB data to be used for the Malaysian AI projects.

**Additional context about yourself (please brag)**
I graduated with a Master's degree in Data Science and Analytics from University of Michigan and since then, I have worked as a Data Analyst for a little over 3 years and then as a Data Science Specialist for almost 2 years. I also founded Wanita Data, a community for Malaysian women in data where we provide a safe space for members to network, collaborate and share knowledge with one another. This community has more than 600 members and more than 2.3k followers across our social media platform since our inception in November 2023. Wanita Data also shares free resources such as educational content on data and sharing sessions to empower more women to break into the data field.

**Comment by huseinzol05** [comment]
<img width="478" alt="Screenshot 2024-04-15 at 11 54 45 AM" src="https://github.com/malaysia-ai/jupyter-gpu/assets/19810909/6ea340c1-5d93-48bf-b853-5af6c54939f4">

after that try https://jupyter.us.mesolitica.com/

**Comment by Elissa-Irhamy** [comment]
received access! thank you :)
