### ISSUE TITLE
Request access to jupyter

### ISSUE THREAD

**Issue by ammarsaf** [malaysia-ai/Jupyterhub#36]
**What is your name?**
Ammar

**What is your title? no need to mention company.**
Data Scientist

**What can you help?**
Scraping, assist current team on sfw model training

**Additional context about yourself (please brag)**
jack of all trade, model training included computer vision, multimodal text classifier, recommender system, tabular data analysis, API, cloud deployment, docker, cicd

**Comment by huseinzol05** [comment]
nooooohhhhhhhhhhhh
