### ISSUE TITLE
Request access to GPU / Jupyter

### ISSUE THREAD

**Issue by kaiimran** [malaysia-ai/Jupyterhub#39]
**What is your name?**
Imran

**What is your title? no need to mention company.**
Business Intelligence & Part-time Freelancer

**What can you help?**
Fine-tuning models, identify good data sources, scraping/crawling, data preprocessing & strategic direction (there are a lot of things to do in AI right now, so what exactly should we focus first?).

**Additional context about yourself (please brag)**
My biggest achievement is being Adha's classmate during CS diploma. https://www.linkedin.com/in/khairulimran99/

On top of that, I have also utilized various web scraping methods in my previous job. E.g. cURL, GraphQL, microdata, JSON-LD, fake Googlebot, rotating IP proxies, PHP DOMDocument & Python BeautifulSoup to extract real-time pricing data.

**Comment by aisyahrzk** [comment]
approved access here https://jupyter.us-east2.mesolitica.com/tree

**Comment by aisyahrzk** [comment]
a

**Comment by aisyahrzk** [comment]
if able to access close the issue
