### ISSUE TITLE
Request access to GPU server

### ISSUE THREAD

**Issue by haizadtarik** [malaysia-ai/Jupyterhub#4]
**What is your name?**
Haizad

**What is your title? no need to mention company.**
Data Scientist

**What can you help?**
Model fine-tuning

**Additional context about yourself (please brag)**
Experienced in ML model development and deployment.

**Comment by huseinzol05** [comment]
I will add the access tonight, AFKKKKK

**Comment by aisyahrzk** [comment]
approved, looking forward to your contributions! @haizadtarik, husein will provide you access

**Comment by huseinzol05** [comment]
@haizadtarik , try access https://jupyter.app.mesolitica.com/, close this issue if able to access.
