### ISSUE TITLE
Request Access

### ISSUE THREAD

**Issue by syafie-nzm** [malaysia-ai/Jupyterhub#6]
**What is your name?**
Syafie
**What is your title? no need to mention company.**
Jobseeker, fresh postgraduate
**What can you help?**
Model training, web scrapping & data mining (nak belajar)
**Additional context about yourself (please brag)**
recently submitted thesis. research background in computer vision to be specific generative ai, basic knowledge on NLP (tak pernah hands-on)

**Comment by huseinzol05** [comment]
share draft or anything.

**Comment by syafie-nzm** [comment]
my thesis/research related ke husein?

**Comment by KamarulAdha** [comment]
Hello Syafie! Kamarul here. Thank you for your interest in our project. Feel free to share any information regarding your work/thesis. We are eager to know more about you and your work. 

Simply contact either of us via Discord ( husein.zolkepli / Raijin) to send the materials. 

Thank you!

Best regards,

**Comment by huseinzol05** [comment]
added!
