### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Ashrafauzi96** [malaysia-ai/Jupyterhub#7]
**What is your name?**
Ashraf
**What is your title? no need to mention company.**
ETL Developer
**What can you help?**
ETL process, develop complex sql queries, data cleaning, building dashboard, develop data pipeline, develop data warehouse
**Additional context about yourself (please brag)**

**Comment by KamarulAdha** [comment]
Hello Ashraf! Kamarul here. Thank you for your interest in our project. We would be so happy to have more people join and contribute to Malaysia.AI. 

Thus, would you mind sharing more of what you are doing now, what kind of tech stack you prefer, or maybe ideas on how you would like to contribute? 

Any additional information would help us out. 

Personal note, are you a fan of Airflow, Mage, Prefer, etc? Let us know.

Thank you.

Best regards,
