### ISSUE TITLE
Request to use Jupyter Notebook GPU - Amirul Azreen 

### ISSUE THREAD

**Issue by amirulazreen** [malaysia-ai/Jupyterhub#8]
**What is your name?**
My name is Amirul Azreen
**What is your title? no need to mention company.**
AI Developer Intern
**What can you help?**
I will look at what can I help on the weekend, as for now I'm struggling with coding.
**Additional context about yourself (please brag)**
A 5 years accountant that joined 1 month of python bootcamp and suddenly instructed to build auto-encoder as intern. This is not a brag, this is a call for help.

**Comment by KamarulAdha** [comment]
Hello Amirul Azreen! Kamarul here. We're excited to have more people contribute to our project. 

Do you mind sharing more of what you have done so far or planning to do? Any plans to contribute to Malaysia.AI?

Feel free to DM us @ either husein.zolkepli or Raijin on Discord. 

Thank you

Best regards,
