### ISSUE TITLE
Request access

### ISSUE THREAD

**Issue by ghost** [malaysia-ai/Jupyterhub#9]
**What is your name?**
My name is Abdul Muhaimin Bin Mustaffa Kamal.

**What is your title? no need to mention company.**
Student.

**What can you help?**
Any help that is needed, but, I need to learn about it first. Because I am a beginner.

**Additional context about yourself (please brag)**
I repeat a semester to finish my final year project. I guess that also counts as bragging.

**Comment by KamarulAdha** [comment]
Due to the account termination, we will assume that you are no longer interested in pursuing our infra. Thank you for your time. 

Best regards,
